### ISSUE TITLE
Training data

### ISSUE THREAD

**Issue by brdhunga** [CharlesAverill/Address-Atomization#1]
Where can I get sample training data ? If there were some sample  examples as comments, that would be great. Thanks

**Comment by CharlesAverill** [comment]
I'll try to find the data I was using, should be able to upload it by tonight.

**Comment by CharlesAverill** [comment]
Here you go! The data in the "CANADA" tab is what I used.

https://github.com/CharlesAverill/Address-Atomization/blob/master/sample_address_dataset.xlsx

**Comment by brdhunga** [comment]
Thanks Charles !!
