### ISSUE TITLE
Re-train the model

### ISSUE THREAD

**Issue by ujjwalgarg** [CharlesAverill/Address-Atomization#3]
My model summary is - 

```
Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_3 (InputLayer)         [(None, 250)]             0         
_________________________________________________________________
embedding_2 (Embedding)      (None, 250, 50)           2250      
_________________________________________________________________
dropout_2 (Dropout)          (None, 250, 50)           0         
_________________________________________________________________
bidirectional_2 (Bidirection (None, 250, 200)          120800    
_________________________________________________________________
time_distributed_1 (TimeDist (None, 250, 14)           2814      
=================================================================
Total params: 125,864
Trainable params: 125,864
Non-trainable params: 0
```

I have reached this point using the following piece of code - 
```
max_len = 250
n_words = len(tokenizer.index_word)
n_tags = len(_labels) + 1

_input = tf.keras.layers.Input(shape=(max_len,))
model = tf.keras.layers.Embedding(input_dim=n_words, output_dim=50, input_length=max_len)(_input)
model = tf.keras.layers.Dropout(0.1)(model)
model = tf.keras.layers.Bidirectional(
    tf.keras.layers.LSTM(units=100, return_sequences=True, recurrent_dropout=0.1)
)(model)
_output = tf.keras.layers.TimeDistributed(
    tf.keras.layers.Dense(n_tags, activation="softmax")
)(model)  # softmax output layer

model = tf.keras.Model(_input, _output)
```
Can you help me with the following error?
<img width="972" alt="Screenshot 2021-08-23 at 1 34 37 PM" src="https://user-images.githubusercontent.com/16412534/130412521-892234b4-3748-42cc-a637-8dd02e67f791.png">

I am using character level tokenizer. Max characters in an address is set at 250.

**Comment by ujjwalgarg** [comment]
I understand that you input X has shape (2500, 20), i.e., for 2500 samples you have maximum 20 words per address.

I am not able to understand what is the rational behind shape of single instance of y. y is a list of numpy arrays with shape (20, 12500). Where is this 12500 coming from? As per my understanding we need to classify 20 words from each sentence into set of 5 possible tags. Should the shape not be (20, 5) ?

**Comment by CharlesAverill** [comment]
@ujjwalgarg I'm sorry, I worked on this project years ago, and as a result most of the code is indecipherable to me now. I wish you luck with your project.
